all: pg_libpq sqlite3_libsqlite3

pg_libpq:
	make -C autoload/vdbc/driver/pg_libpq/ -f Makefile.win64

sqlite3_libsqlite3:
	make -C autoload/vdbc/driver/sqlite3_libsqlite3/ -f Makefile.win64

clean:
	make -C autoload/vdbc/driver/pg_libpq/ -f Makefile.win64 clean
	make -C autoload/vdbc/driver/sqlite3_libsqlite3/ -f Makefile.win64 clean
