CXX=x86_64-w64-mingw32-g++
CXXFLAGS=-std=c++0x -Wall -O2 --shared
SRC=pg_libpq.cpp
TARGET=../pg_libpq.dll
LDFLAGS=-lpq
INCDIR=
LIBDIR=

all: pg_libpq

pg_libpq:
	${CXX} ${CXXFLAGS} ${INCDIR} -o ${TARGET} ${SRC} ${LIBDIR} ${LDFLAGS}

clean:
	${RM} ${TARGET}
